-- bojo24 데이터베이스 스키마
-- Supabase SQL Editor에서 실행

-- 1. benefits 테이블 (보조금 정보)
CREATE TABLE IF NOT EXISTS benefits (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  governing_org TEXT,
  detail_json JSONB NOT NULL,
  last_updated_at TIMESTAMPTZ DEFAULT NOW(),
  gemini_summary TEXT,
  gemini_faq_json JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스 생성 (검색 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_benefits_category ON benefits(category);
CREATE INDEX IF NOT EXISTS idx_benefits_governing_org ON benefits(governing_org);
CREATE INDEX IF NOT EXISTS idx_benefits_last_updated ON benefits(last_updated_at DESC);
-- 한국어 텍스트 검색 인덱스 (simple 설정 사용 - Supabase 기본)
CREATE INDEX IF NOT EXISTS idx_benefits_name_search ON benefits USING gin(to_tsvector('simple', name));

-- JSONB 인덱스 (상세 검색용)
CREATE INDEX IF NOT EXISTS idx_benefits_detail_json ON benefits USING gin(detail_json);

-- 2. posts 테이블 (블로그 포스트 - 고유 컨텐츠)
CREATE TABLE IF NOT EXISTS posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  benefit_id TEXT REFERENCES benefits(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT,
  tags TEXT[] DEFAULT '{}',
  seo_keywords TEXT[] DEFAULT '{}',
  meta_description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  published_at TIMESTAMPTZ,
  is_published BOOLEAN DEFAULT true,
  view_count INTEGER DEFAULT 0,
  -- 중복 방지: 같은 benefit_id로 여러 포스트 생성 방지
  UNIQUE(benefit_id, slug)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
CREATE INDEX IF NOT EXISTS idx_posts_benefit_id ON posts(benefit_id);
CREATE INDEX IF NOT EXISTS idx_posts_published ON posts(is_published, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_tags ON posts USING gin(tags);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);

-- 3. content_duplicates 테이블 (중복 컨텐츠 방지)
CREATE TABLE IF NOT EXISTS content_duplicates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_hash TEXT UNIQUE NOT NULL, -- 컨텐츠 해시값
  content_type TEXT NOT NULL, -- 'benefit' or 'post'
  content_id TEXT NOT NULL, -- benefit.id or post.id
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_duplicates_hash ON content_duplicates(content_hash);
CREATE INDEX IF NOT EXISTS idx_content_duplicates_type ON content_duplicates(content_type, content_id);

-- 4. seo_metadata 테이블 (SEO 메타데이터 캐싱)
CREATE TABLE IF NOT EXISTS seo_metadata (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  page_type TEXT NOT NULL, -- 'benefit', 'post', 'page'
  page_id TEXT NOT NULL,
  canonical_url TEXT NOT NULL,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  structured_data JSONB, -- 구조화 데이터 (JSON-LD)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(page_type, page_id)
);

CREATE INDEX IF NOT EXISTS idx_seo_metadata_page ON seo_metadata(page_type, page_id);
CREATE INDEX IF NOT EXISTS idx_seo_metadata_canonical ON seo_metadata(canonical_url);

-- 5. admin_settings 테이블 (기존)
CREATE TABLE IF NOT EXISTS admin_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. page_views 테이블 (기존)
CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL,
  ip_hash TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_page_views_path ON page_views(path);
CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON page_views(created_at DESC);

-- RLS (Row Level Security) 정책 설정
ALTER TABLE benefits ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_duplicates ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_views ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제 (중복 실행 방지)
DROP POLICY IF EXISTS "Public read benefits" ON benefits;
DROP POLICY IF EXISTS "Public read posts" ON posts;
DROP POLICY IF EXISTS "Public read seo_metadata" ON seo_metadata;
DROP POLICY IF EXISTS "Public insert page_views" ON page_views;
DROP POLICY IF EXISTS "Admin full access benefits" ON benefits;
DROP POLICY IF EXISTS "Admin full access posts" ON posts;
DROP POLICY IF EXISTS "Admin full access content_duplicates" ON content_duplicates;
DROP POLICY IF EXISTS "Admin full access seo_metadata" ON seo_metadata;
DROP POLICY IF EXISTS "Admin full access admin_settings" ON admin_settings;
DROP POLICY IF EXISTS "Admin full access page_views" ON page_views;

-- 공개 읽기 정책
CREATE POLICY "Public read benefits" ON benefits FOR SELECT USING (true);
CREATE POLICY "Public read posts" ON posts FOR SELECT USING (is_published = true);
CREATE POLICY "Public read seo_metadata" ON seo_metadata FOR SELECT USING (true);

-- 공개 쓰기 정책 (페이지뷰 등)
CREATE POLICY "Public insert page_views" ON page_views FOR INSERT WITH CHECK (true);

-- 관리자 정책 (Service Role만 접근)
CREATE POLICY "Admin full access benefits" ON benefits USING (true);
CREATE POLICY "Admin full access posts" ON posts USING (true);
CREATE POLICY "Admin full access content_duplicates" ON content_duplicates USING (true);
CREATE POLICY "Admin full access seo_metadata" ON seo_metadata USING (true);
CREATE POLICY "Admin full access admin_settings" ON admin_settings USING (true);
CREATE POLICY "Admin full access page_views" ON page_views USING (true);

-- 업데이트 트리거 함수 (updated_at 자동 갱신)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 트리거 생성
CREATE TRIGGER update_benefits_updated_at BEFORE UPDATE ON benefits
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_seo_metadata_updated_at BEFORE UPDATE ON seo_metadata
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 뷰 생성 (검색 최적화)
CREATE OR REPLACE VIEW benefits_search_view AS
SELECT 
  id,
  name,
  category,
  governing_org,
  gemini_summary,
  last_updated_at,
  to_tsvector('simple', COALESCE(name, '') || ' ' || COALESCE(category, '') || ' ' || COALESCE(governing_org, '') || ' ' || COALESCE(gemini_summary, '')) AS search_vector
FROM benefits;

-- 검색 함수
CREATE OR REPLACE FUNCTION search_benefits(query_text TEXT)
RETURNS TABLE (
  id TEXT,
  name TEXT,
  category TEXT,
  governing_org TEXT,
  rank REAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    b.id,
    b.name,
    b.category,
    b.governing_org,
    ts_rank(bv.search_vector, plainto_tsquery('simple', query_text)) AS rank
  FROM benefits_search_view bv
  JOIN benefits b ON bv.id = b.id
  WHERE bv.search_vector @@ plainto_tsquery('simple', query_text)
  ORDER BY rank DESC
  LIMIT 50;
END;
$$ LANGUAGE plpgsql;

