-- 1. 사이트 전역 설정 테이블 (Head 스크립트 등 저장)
create table if not exists admin_settings (
  key text primary key,
  value text,
  updated_at timestamptz default now()
);

-- 2. 방문자 로그 테이블 (간이 애널리틱스)
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  ip_hash text, -- 선택적 익명화된 IP
  user_agent text,
  created_at timestamptz default now()
);

-- RLS (보안 정책) 설정
alter table admin_settings enable row level security;
alter table page_views enable row level security;

-- 기존 정책 삭제 (중복 실행 방지)
DROP POLICY IF EXISTS "Public read settings" ON admin_settings;
DROP POLICY IF EXISTS "Public insert views" ON page_views;
DROP POLICY IF EXISTS "Admin full access settings" ON admin_settings;
DROP POLICY IF EXISTS "Admin full access views" ON page_views;

-- 누구나 설정 읽기 가능 (Head 스크립트 로딩용)
create policy "Public read settings" on admin_settings for select using (true);

-- 누구나 로그 쌓기 가능 (방문자 추적용)
create policy "Public insert views" on page_views for insert with check (true);

-- 관리자(Service Role)만 모든 권한
create policy "Admin full access settings" on admin_settings using (true);
create policy "Admin full access views" on page_views using (true);
