-- bojo24 Supabase 완전 설정 스크립트
-- 중복 실행에 안전하게 모든 정책을 DROP 후 재생성
-- 이 파일 하나만 실행하면 모든 스키마가 설정됩니다.

-- ============================================
-- 1. 관리 테이블 및 정책
-- ============================================

-- 테이블 생성
CREATE TABLE IF NOT EXISTS admin_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL,
  ip_hash TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS 활성화
ALTER TABLE admin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_views ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제
DROP POLICY IF EXISTS "Public read settings" ON admin_settings;
DROP POLICY IF EXISTS "Public insert views" ON page_views;
DROP POLICY IF EXISTS "Admin full access settings" ON admin_settings;
DROP POLICY IF EXISTS "Admin full access views" ON page_views;

-- 정책 재생성
CREATE POLICY "Public read settings" ON admin_settings FOR SELECT USING (true);
CREATE POLICY "Public insert views" ON page_views FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin full access settings" ON admin_settings USING (true);
CREATE POLICY "Admin full access views" ON page_views USING (true);

-- ============================================
-- 2. 메인 스키마 (benefits, posts 등)
-- ============================================

-- benefits 테이블
CREATE TABLE IF NOT EXISTS benefits (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  governing_org TEXT,
  detail_json JSONB NOT NULL,
  last_updated_at TIMESTAMPTZ DEFAULT NOW(),
  gemini_summary TEXT,
  gemini_faq_json JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- posts 테이블
CREATE TABLE IF NOT EXISTS posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  benefit_id TEXT REFERENCES benefits(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT,
  tags TEXT[] DEFAULT '{}',
  seo_keywords TEXT[] DEFAULT '{}',
  meta_description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  published_at TIMESTAMPTZ,
  is_published BOOLEAN DEFAULT true,
  view_count INTEGER DEFAULT 0,
  UNIQUE(benefit_id, slug)
);

-- 기존 테이블에 컬럼이 없으면 추가 (마이그레이션 안전성)
DO $$
BEGIN
  -- is_published 컬럼 추가 (없는 경우)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'posts' AND column_name = 'is_published'
  ) THEN
    ALTER TABLE posts ADD COLUMN is_published BOOLEAN DEFAULT true;
  END IF;
  
  -- published_at 컬럼 추가 (없는 경우)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'posts' AND column_name = 'published_at'
  ) THEN
    ALTER TABLE posts ADD COLUMN published_at TIMESTAMPTZ;
  END IF;
  
  -- view_count 컬럼 추가 (없는 경우)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'posts' AND column_name = 'view_count'
  ) THEN
    ALTER TABLE posts ADD COLUMN view_count INTEGER DEFAULT 0;
  END IF;
END $$;

-- content_duplicates 테이블
CREATE TABLE IF NOT EXISTS content_duplicates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_hash TEXT UNIQUE NOT NULL,
  content_type TEXT NOT NULL,
  content_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- seo_metadata 테이블
CREATE TABLE IF NOT EXISTS seo_metadata (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  page_type TEXT NOT NULL,
  page_id TEXT NOT NULL,
  canonical_url TEXT NOT NULL,
  og_title TEXT,
  og_description TEXT,
  og_image TEXT,
  structured_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(page_type, page_id)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_benefits_category ON benefits(category);
CREATE INDEX IF NOT EXISTS idx_benefits_governing_org ON benefits(governing_org);
CREATE INDEX IF NOT EXISTS idx_benefits_last_updated ON benefits(last_updated_at DESC);
-- 한국어 텍스트 검색 인덱스 (simple 설정 사용 - Supabase 기본)
CREATE INDEX IF NOT EXISTS idx_benefits_name_search ON benefits USING gin(to_tsvector('simple', name));
CREATE INDEX IF NOT EXISTS idx_benefits_detail_json ON benefits USING gin(detail_json);
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
CREATE INDEX IF NOT EXISTS idx_posts_benefit_id ON posts(benefit_id);
CREATE INDEX IF NOT EXISTS idx_posts_published ON posts(is_published, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_tags ON posts USING gin(tags);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_duplicates_hash ON content_duplicates(content_hash);
CREATE INDEX IF NOT EXISTS idx_content_duplicates_type ON content_duplicates(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_seo_metadata_page ON seo_metadata(page_type, page_id);
CREATE INDEX IF NOT EXISTS idx_seo_metadata_canonical ON seo_metadata(canonical_url);
CREATE INDEX IF NOT EXISTS idx_page_views_path ON page_views(path);
CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON page_views(created_at DESC);

-- RLS 활성화
ALTER TABLE benefits ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_duplicates ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_metadata ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제
DROP POLICY IF EXISTS "Public read benefits" ON benefits;
DROP POLICY IF EXISTS "Public read posts" ON posts;
DROP POLICY IF EXISTS "Public read seo_metadata" ON seo_metadata;
DROP POLICY IF EXISTS "Public insert page_views" ON page_views;
DROP POLICY IF EXISTS "Admin full access benefits" ON benefits;
DROP POLICY IF EXISTS "Admin full access posts" ON posts;
DROP POLICY IF EXISTS "Admin full access content_duplicates" ON content_duplicates;
DROP POLICY IF EXISTS "Admin full access seo_metadata" ON seo_metadata;

-- 정책 재생성
CREATE POLICY "Public read benefits" ON benefits FOR SELECT USING (true);
CREATE POLICY "Public read posts" ON posts
  FOR SELECT
  USING (
    is_published = true
    AND (
      published_at IS NULL
      OR published_at <= NOW()
    )
  );
CREATE POLICY "Public read seo_metadata" ON seo_metadata FOR SELECT USING (true);
CREATE POLICY "Public insert page_views" ON page_views FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin full access benefits" ON benefits USING (true);
CREATE POLICY "Admin full access posts" ON posts USING (true);
CREATE POLICY "Admin full access content_duplicates" ON content_duplicates USING (true);
CREATE POLICY "Admin full access seo_metadata" ON seo_metadata USING (true);

-- ============================================
-- 3. 템플릿 시스템 스키마
-- ============================================

-- content_templates 테이블
CREATE TABLE IF NOT EXISTS content_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  template_type TEXT NOT NULL,
  template_content JSONB NOT NULL,
  variables JSONB DEFAULT '{}',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- benefit_content 테이블
CREATE TABLE IF NOT EXISTS benefit_content (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  benefit_id TEXT NOT NULL REFERENCES benefits(id) ON DELETE CASCADE,
  template_id UUID REFERENCES content_templates(id),
  content_type TEXT NOT NULL,
  intro_text TEXT,
  analysis_text TEXT,
  guide_text TEXT,
  tips_text TEXT,
  comparison_text TEXT,
  content_hash TEXT,
  uniqueness_score REAL DEFAULT 0,
  word_count INTEGER DEFAULT 0,
  generated_by TEXT DEFAULT 'ai',
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(benefit_id, content_type)
);

-- content_sections 테이블
CREATE TABLE IF NOT EXISTS content_sections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  benefit_content_id UUID NOT NULL REFERENCES benefit_content(id) ON DELETE CASCADE,
  section_type TEXT NOT NULL,
  section_order INTEGER DEFAULT 0,
  title TEXT,
  content TEXT NOT NULL,
  content_hash TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- template_variables 테이블
CREATE TABLE IF NOT EXISTS template_variables (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id UUID REFERENCES content_templates(id) ON DELETE CASCADE,
  variable_name TEXT NOT NULL,
  variable_type TEXT NOT NULL,
  default_value TEXT,
  description TEXT,
  is_required BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_benefit_content_benefit_id ON benefit_content(benefit_id);
CREATE INDEX IF NOT EXISTS idx_benefit_content_type ON benefit_content(content_type);
CREATE INDEX IF NOT EXISTS idx_benefit_content_hash ON benefit_content(content_hash);
CREATE INDEX IF NOT EXISTS idx_benefit_content_uniqueness ON benefit_content(uniqueness_score DESC);
CREATE INDEX IF NOT EXISTS idx_content_sections_benefit_content ON content_sections(benefit_content_id);
CREATE INDEX IF NOT EXISTS idx_content_sections_type ON content_sections(section_type);
CREATE INDEX IF NOT EXISTS idx_template_variables_template ON template_variables(template_id);

-- RLS 활성화
ALTER TABLE content_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE benefit_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_variables ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제
DROP POLICY IF EXISTS "Public read templates" ON content_templates;
DROP POLICY IF EXISTS "Public read benefit_content" ON benefit_content;
DROP POLICY IF EXISTS "Public read content_sections" ON content_sections;
DROP POLICY IF EXISTS "Public read template_variables" ON template_variables;
DROP POLICY IF EXISTS "Admin full access templates" ON content_templates;
DROP POLICY IF EXISTS "Admin full access benefit_content" ON benefit_content;
DROP POLICY IF EXISTS "Admin full access content_sections" ON content_sections;
DROP POLICY IF EXISTS "Admin full access template_variables" ON template_variables;

-- 정책 재생성
CREATE POLICY "Public read templates" ON content_templates FOR SELECT USING (is_active = true);
CREATE POLICY "Public read benefit_content" ON benefit_content FOR SELECT USING (true);
CREATE POLICY "Public read content_sections" ON content_sections FOR SELECT USING (true);
CREATE POLICY "Public read template_variables" ON template_variables FOR SELECT USING (true);
CREATE POLICY "Admin full access templates" ON content_templates USING (true);
CREATE POLICY "Admin full access benefit_content" ON benefit_content USING (true);
CREATE POLICY "Admin full access content_sections" ON content_sections USING (true);
CREATE POLICY "Admin full access template_variables" ON template_variables USING (true);

-- ============================================
-- 4. 함수 및 트리거
-- ============================================

-- updated_at 자동 갱신 함수
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 트리거 생성
DROP TRIGGER IF EXISTS update_benefits_updated_at ON benefits;
CREATE TRIGGER update_benefits_updated_at BEFORE UPDATE ON benefits
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_seo_metadata_updated_at ON seo_metadata;
CREATE TRIGGER update_seo_metadata_updated_at BEFORE UPDATE ON seo_metadata
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_content_templates_updated_at ON content_templates;
CREATE TRIGGER update_content_templates_updated_at BEFORE UPDATE ON content_templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_benefit_content_updated_at ON benefit_content;
CREATE TRIGGER update_benefit_content_updated_at BEFORE UPDATE ON benefit_content
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_content_sections_updated_at ON content_sections;
CREATE TRIGGER update_content_sections_updated_at BEFORE UPDATE ON content_sections
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 5. 뷰 및 함수
-- ============================================

-- 검색 뷰
CREATE OR REPLACE VIEW benefits_search_view AS
SELECT 
  id,
  name,
  category,
  governing_org,
  gemini_summary,
  last_updated_at,
  to_tsvector('simple', COALESCE(name, '') || ' ' || COALESCE(category, '') || ' ' || COALESCE(governing_org, '') || ' ' || COALESCE(gemini_summary, '')) AS search_vector
FROM benefits;

-- 검색 함수
CREATE OR REPLACE FUNCTION search_benefits(query_text TEXT)
RETURNS TABLE (
  id TEXT,
  name TEXT,
  category TEXT,
  governing_org TEXT,
  rank REAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    b.id,
    b.name,
    b.category,
    b.governing_org,
    ts_rank(bv.search_vector, plainto_tsquery('simple', query_text)) AS rank
  FROM benefits_search_view bv
  JOIN benefits b ON bv.id = b.id
  WHERE bv.search_vector @@ plainto_tsquery('simple', query_text)
  ORDER BY rank DESC
  LIMIT 50;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 6. 기본 데이터 삽입
-- ============================================

-- 기본 템플릿 삽입
INSERT INTO content_templates (name, description, template_type, template_content, variables) VALUES
(
  '기본 상세페이지',
  '표준 보조금 상세페이지 템플릿',
  'detail_page',
  '{
    "sections": [
      {"type": "intro", "order": 1, "required": true},
      {"type": "target", "order": 2, "required": true},
      {"type": "benefit", "order": 3, "required": true},
      {"type": "apply", "order": 4, "required": true},
      {"type": "documents", "order": 5, "required": false},
      {"type": "timeline", "order": 6, "required": false},
      {"type": "tips", "order": 7, "required": false}
    ]
  }'::jsonb,
  '{
    "benefit_name": {"type": "text", "source": "benefit.name"},
    "category": {"type": "text", "source": "benefit.category"},
    "governing_org": {"type": "text", "source": "benefit.governing_org"},
    "target_audience": {"type": "text", "source": "detail.detail.지원대상"},
    "benefit_content": {"type": "text", "source": "detail.detail.지원내용"},
    "apply_method": {"type": "text", "source": "detail.detail.신청방법"},
    "contact": {"type": "text", "source": "detail.detail.문의처"}
  }'::jsonb
) ON CONFLICT (name) DO NOTHING;

-- ============================================
-- 완료 메시지
-- ============================================

DO $$
BEGIN
  RAISE NOTICE '✅ bojo24 데이터베이스 스키마 설정이 완료되었습니다!';
  RAISE NOTICE '📊 다음 테이블이 생성되었습니다:';
  RAISE NOTICE '   - benefits, posts, content_duplicates, seo_metadata';
  RAISE NOTICE '   - admin_settings, page_views';
  RAISE NOTICE '   - content_templates, benefit_content, content_sections, template_variables';
END $$;

